#!/bin/bash
# My first Script

#sampleText.txt= $1

echo "This script runs a Simple Map Reduce program"

#change the directory to the specific file folder
 cd /Users/labuew/Desktop/wordCountProgram

#this compile a java program
javac Splitter.java
javac Stemmer02.java
javac Mapper.java
javac Mapper03.java

echo "hello world " > newData.txt

#excecute the compile files and pipe the output of one into the input of another
java Splitter "sampleText.txt" "10" "1" | java Stemmer02 | java Mapper03 > newData.txt
#java Splitter "sampleText.txt" "10" "2" > newData.txt
#java Splitter "sampleText.txt" "10" "3" | java Stemmer02 | java Mapper03 > newData.txt
#java Splitter "sampleText.txt" "10" "4" > newData.txt

echo "hello"





